package ee.oyatl.ime.keyboard.layout

import android.view.KeyEvent

object LayoutCangjie {

    val TABLE_QWERTY = mapOf(
        KeyEvent.KEYCODE_Q to listOf('手'.code, 'Q'.code),
        KeyEvent.KEYCODE_W to listOf('田'.code, 'W'.code),
        KeyEvent.KEYCODE_E to listOf('水'.code, 'E'.code),
        KeyEvent.KEYCODE_R to listOf('口'.code, 'R'.code),
        KeyEvent.KEYCODE_T to listOf('廿'.code, 'T'.code),
        KeyEvent.KEYCODE_Y to listOf('卜'.code, 'Y'.code),
        KeyEvent.KEYCODE_U to listOf('山'.code, 'U'.code),
        KeyEvent.KEYCODE_I to listOf('戈'.code, 'I'.code),
        KeyEvent.KEYCODE_O to listOf('人'.code, 'O'.code),
        KeyEvent.KEYCODE_P to listOf('心'.code, 'P'.code),

        KeyEvent.KEYCODE_A to listOf('日'.code, 'A'.code),
        KeyEvent.KEYCODE_S to listOf('尸'.code, 'S'.code),
        KeyEvent.KEYCODE_D to listOf('木'.code, 'D'.code),
        KeyEvent.KEYCODE_F to listOf('火'.code, 'F'.code),
        KeyEvent.KEYCODE_G to listOf('土'.code, 'G'.code),
        KeyEvent.KEYCODE_H to listOf('竹'.code, 'H'.code),
        KeyEvent.KEYCODE_J to listOf('十'.code, 'J'.code),
        KeyEvent.KEYCODE_K to listOf('大'.code, 'K'.code),
        KeyEvent.KEYCODE_L to listOf('中'.code, 'L'.code),

        KeyEvent.KEYCODE_Z to listOf('重'.code, 'Z'.code),
        KeyEvent.KEYCODE_X to listOf('難'.code, 'X'.code),
        KeyEvent.KEYCODE_C to listOf('金'.code, 'C'.code),
        KeyEvent.KEYCODE_V to listOf('女'.code, 'V'.code),
        KeyEvent.KEYCODE_B to listOf('月'.code, 'B'.code),
        KeyEvent.KEYCODE_N to listOf('弓'.code, 'N'.code),
        KeyEvent.KEYCODE_M to listOf('一'.code, 'M'.code)
    )

    val TABLE_DAYI3 = mapOf(
        KeyEvent.KEYCODE_GRAVE to listOf('巷'.code, '`'.code),
        KeyEvent.KEYCODE_1 to listOf('言'.code, '!'.code),
        KeyEvent.KEYCODE_2 to listOf('牛'.code, '@'.code),
        KeyEvent.KEYCODE_3 to listOf('目'.code, '#'.code),
        KeyEvent.KEYCODE_4 to listOf('四'.code, '$'.code),
        KeyEvent.KEYCODE_5 to listOf('王'.code, '%'.code),
        KeyEvent.KEYCODE_6 to listOf('門'.code, '^'.code),
        KeyEvent.KEYCODE_7 to listOf('田'.code, '&'.code),
        KeyEvent.KEYCODE_8 to listOf('米'.code, '*'.code),
        KeyEvent.KEYCODE_9 to listOf('足'.code, '('.code),
        KeyEvent.KEYCODE_0 to listOf('金'.code, ')'.code),
        KeyEvent.KEYCODE_MINUS to listOf('郷'.code, '-'.code),
        KeyEvent.KEYCODE_EQUALS to listOf('='.code, '='.code),

        KeyEvent.KEYCODE_Q to listOf('石'.code, 'Q'.code),
        KeyEvent.KEYCODE_W to listOf('山'.code, 'W'.code),
        KeyEvent.KEYCODE_E to listOf('一'.code, 'E'.code),
        KeyEvent.KEYCODE_R to listOf('工'.code, 'R'.code),
        KeyEvent.KEYCODE_T to listOf('糸'.code, 'T'.code),
        KeyEvent.KEYCODE_Y to listOf('火'.code, 'Y'.code),
        KeyEvent.KEYCODE_U to listOf('艸'.code, 'U'.code),
        KeyEvent.KEYCODE_I to listOf('木'.code, 'I'.code),
        KeyEvent.KEYCODE_O to listOf('口'.code, 'O'.code),
        KeyEvent.KEYCODE_P to listOf('耳'.code, 'P'.code),
        KeyEvent.KEYCODE_LEFT_BRACKET to listOf('路'.code, '['.code),
        KeyEvent.KEYCODE_RIGHT_BRACKET to listOf('街'.code, ']'.code),
        KeyEvent.KEYCODE_BACKSLASH to listOf('鎮'.code, '\\'.code),

        KeyEvent.KEYCODE_A to listOf('人'.code, 'A'.code),
        KeyEvent.KEYCODE_S to listOf('革'.code, 'S'.code),
        KeyEvent.KEYCODE_D to listOf('日'.code, 'D'.code),
        KeyEvent.KEYCODE_F to listOf('土'.code, 'F'.code),
        KeyEvent.KEYCODE_G to listOf('手'.code, 'G'.code),
        KeyEvent.KEYCODE_H to listOf('鳥'.code, 'H'.code),
        KeyEvent.KEYCODE_J to listOf('月'.code, 'J'.code),
        KeyEvent.KEYCODE_K to listOf('立'.code, 'K'.code),
        KeyEvent.KEYCODE_L to listOf('女'.code, 'L'.code),
        KeyEvent.KEYCODE_SEMICOLON to listOf('虫'.code, ';'.code),
        KeyEvent.KEYCODE_APOSTROPHE to listOf('號'.code, '\''.code),

        KeyEvent.KEYCODE_Z to listOf('心'.code, 'Z'.code),
        KeyEvent.KEYCODE_X to listOf('水'.code, 'X'.code),
        KeyEvent.KEYCODE_C to listOf('鹿'.code, 'C'.code),
        KeyEvent.KEYCODE_V to listOf('禾'.code, 'V'.code),
        KeyEvent.KEYCODE_B to listOf('馬'.code, 'B'.code),
        KeyEvent.KEYCODE_N to listOf('魚'.code, 'N'.code),
        KeyEvent.KEYCODE_M to listOf('雨'.code, 'M'.code),
        KeyEvent.KEYCODE_COMMA to listOf('力'.code, ','.code),
        KeyEvent.KEYCODE_PERIOD to listOf('舟'.code, '.'.code),
        KeyEvent.KEYCODE_SLASH to listOf('竹'.code, '/'.code),
    )

    val KEY_MAP_CANGJIE = mapOf(
        '日' to 'a',
        '月' to 'b',
        '金' to 'c',
        '木' to 'd',
        '水' to 'e',
        '火' to 'f',
        '土' to 'g',
        '竹' to 'h',
        '戈' to 'i',
        '十' to 'j',
        '大' to 'k',
        '中' to 'l',
        '一' to 'm',
        '弓' to 'n',
        '人' to 'o',
        '心' to 'p',
        '手' to 'q',
        '口' to 'r',
        '尸' to 's',
        '廿' to 't',
        '山' to 'u',
        '女' to 'v',
        '田' to 'w',
        '難' to 'x',
        '卜' to 'y',
        '重' to 'z'
    )

    val KEY_MAP_DAYI3 = mapOf(
        '巷' to '`',
        '言' to '1',
        '牛' to '2',
        '目' to '3',
        '四' to '4',
        '王' to '5',
        '門' to '6',
        '田' to '7',
        '米' to '8',
        '足' to '9',
        '金' to '0',
        '郷' to '-',
        '石' to 'Q',
        '山' to 'W',
        '一' to 'E',
        '工' to 'R',
        '糸' to 'T',
        '火' to 'Y',
        '艸' to 'U',
        '木' to 'I',
        '口' to 'O',
        '耳' to 'P',
        '路' to '[',
        '街' to ']',
        '鎮' to '\\',
        '人' to 'A',
        '革' to 'S',
        '日' to 'D',
        '土' to 'F',
        '手' to 'G',
        '鳥' to 'H',
        '月' to 'J',
        '立' to 'K',
        '女' to 'L',
        '虫' to ';',
        '號' to '\'',
        '心' to 'Z',
        '水' to 'X',
        '鹿' to 'C',
        '禾' to 'V',
        '馬' to 'B',
        '魚' to 'N',
        '雨' to 'M',
        '力' to ',',
        '舟' to '.',
        '竹' to '/'
    )

}