package ee.oyatl.ime.fusion.layout

import android.view.KeyEvent

object LayoutZhuyin {
    val TABLE = mapOf(
        KeyEvent.KEYCODE_1 to listOf('ㄅ'.code, '！'.code),
        KeyEvent.KEYCODE_2 to listOf('ㄉ'.code, '@'.code),
        KeyEvent.KEYCODE_3 to listOf('ˇ'.code, '#'.code),
        KeyEvent.KEYCODE_4 to listOf('ˋ'.code, '￥'.code),
        KeyEvent.KEYCODE_5 to listOf('ㄓ'.code, '%'.code),
        KeyEvent.KEYCODE_6 to listOf('ˊ'.code, '…'.code),
        KeyEvent.KEYCODE_7 to listOf('˙'.code, '&'.code),
        KeyEvent.KEYCODE_8 to listOf('ㄚ'.code, '*'.code),
        KeyEvent.KEYCODE_9 to listOf('ㄞ'.code, '（'.code),
        KeyEvent.KEYCODE_0 to listOf('ㄢ'.code, '）'.code),

        KeyEvent.KEYCODE_Q to listOf('ㄆ'.code, 'Q'.code),
        KeyEvent.KEYCODE_W to listOf('ㄊ'.code, 'W'.code),
        KeyEvent.KEYCODE_E to listOf('ㄍ'.code, 'E'.code),
        KeyEvent.KEYCODE_R to listOf('ㄐ'.code, 'R'.code),
        KeyEvent.KEYCODE_T to listOf('ㄔ'.code, 'T'.code),
        KeyEvent.KEYCODE_Y to listOf('ㄗ'.code, 'Y'.code),
        KeyEvent.KEYCODE_U to listOf('ㄧ'.code, 'U'.code),
        KeyEvent.KEYCODE_I to listOf('ㄛ'.code, 'I'.code),
        KeyEvent.KEYCODE_O to listOf('ㄟ'.code, 'O'.code),
        KeyEvent.KEYCODE_P to listOf('ㄣ'.code, 'P'.code),

        KeyEvent.KEYCODE_A to listOf('ㄇ'.code, 'A'.code),
        KeyEvent.KEYCODE_S to listOf('ㄋ'.code, 'S'.code),
        KeyEvent.KEYCODE_D to listOf('ㄎ'.code, 'D'.code),
        KeyEvent.KEYCODE_F to listOf('ㄑ'.code, 'F'.code),
        KeyEvent.KEYCODE_G to listOf('ㄕ'.code, 'G'.code),
        KeyEvent.KEYCODE_H to listOf('ㄘ'.code, 'H'.code),
        KeyEvent.KEYCODE_J to listOf('ㄨ'.code, 'J'.code),
        KeyEvent.KEYCODE_K to listOf('ㄜ'.code, 'K'.code),
        KeyEvent.KEYCODE_L to listOf('ㄠ'.code, 'L'.code),
        KeyEvent.KEYCODE_SEMICOLON to listOf('ㄤ'.code, '：'.code),

        KeyEvent.KEYCODE_Z to listOf('ㄈ'.code, 'Z'.code),
        KeyEvent.KEYCODE_X to listOf('ㄌ'.code, 'X'.code),
        KeyEvent.KEYCODE_C to listOf('ㄏ'.code, 'C'.code),
        KeyEvent.KEYCODE_V to listOf('ㄒ'.code, 'V'.code),
        KeyEvent.KEYCODE_B to listOf('ㄖ'.code, 'B'.code),
        KeyEvent.KEYCODE_N to listOf('ㄙ'.code, 'N'.code),
        KeyEvent.KEYCODE_M to listOf('ㄩ'.code, 'M'.code),
        KeyEvent.KEYCODE_COMMA to listOf('ㄝ'.code, '，'.code),
        KeyEvent.KEYCODE_PERIOD to listOf('ㄡ'.code, '。'.code),
        KeyEvent.KEYCODE_SLASH to listOf('ㄥ'.code, '？'.code),
        KeyEvent.KEYCODE_MINUS to listOf('ㄦ'.code, '—'.code)
    )

    val TONE_MARKS = setOf('ˉ', 'ˇ', 'ˋ', 'ˊ', '˙')

    val CODES_MAP = mapOf(
        'ㄅ' to '1',
        'ㄉ' to '2',
        'ˇ' to '3',
        'ˋ' to '4',
        'ㄓ' to '5',
        'ˊ' to '6',
        '˙' to '7',
        'ㄚ' to '8',
        'ㄞ' to '9',
        'ㄢ' to '0',
        'ㄆ' to 'q',
        'ㄊ' to 'w',
        'ㄍ' to 'e',
        'ㄐ' to 'r',
        'ㄔ' to 't',
        'ㄗ' to 'y',
        'ㄧ' to 'u',
        'ㄛ' to 'i',
        'ㄟ' to 'o',
        'ㄣ' to 'p',
        'ㄇ' to 'a',
        'ㄋ' to 's',
        'ㄎ' to 'd',
        'ㄑ' to 'f',
        'ㄕ' to 'g',
        'ㄘ' to 'h',
        'ㄨ' to 'j',
        'ㄜ' to 'k',
        'ㄠ' to 'l',
        'ㄤ' to ';',
        'ㄈ' to 'z',
        'ㄌ' to 'x',
        'ㄏ' to 'c',
        'ㄒ' to 'v',
        'ㄖ' to 'b',
        'ㄙ' to 'n',
        'ㄩ' to 'm',
        'ㄝ' to ',',
        'ㄡ' to '.',
        'ㄥ' to '/',
        'ㄦ' to '-',
        'ˉ' to ' '
    )
}