/*
 * Copyright (C) 2009 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.inputmethod.pinyin

import android.content.Context
import android.content.res.Configuration
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Paint.FontMetricsInt
import android.graphics.RectF
import android.graphics.drawable.Drawable
import android.os.Handler
import android.util.AttributeSet
import android.view.GestureDetector
import android.view.MotionEvent
import android.view.View
import com.android.inputmethod.pinyin.PinyinIME.DecodingInfo
import ee.oyatl.ime.fusion.R
import java.util.Vector

/**
 * View to show candidate list. There two candidate view instances which are
 * used to show animation when user navigates between pages.
 */
class CandidateView(context: Context, attrs: AttributeSet?) :
    View(context, attrs) {
    /**
     * The width to draw candidates.
     */
    private var mContentWidth = 0

    /**
     * The height to draw candidate content.
     */
    private var mContentHeight = 0

    /**
     * Whether footnotes are displayed. Footnote is shown when hardware keyboard
     * is available.
     */
    private var mShowFootnote = true

    /**
     * Balloon hint for candidate press/release.
     */
    private var mBalloonHint: BalloonHint? = null

    /**
     * Desired position of the balloon to the input view.
     */
    private val mHintPositionToInputView = IntArray(2)

    /**
     * Decoding result to show.
     */
    private var mDecInfo: DecodingInfo? = null

    /**
     * Listener used to notify IME that user clicks a candidate, or navigate
     * between them.
     */
    private var mCvListener: CandidateViewListener? = null

    /**
     * Used to notify the container to update the status of forward/backward
     * arrows.
     */
    private var mArrowUpdater: ArrowUpdater? = null

    /**
     * If true, update the arrow status when drawing candidates.
     */
    private var mUpdateArrowStatusWhenDraw = false

    /**
     * Page number of the page displayed in this view.
     */
    private var mPageNo = 0

    /**
     * Active candidate position in this page.
     */
    var activeCandiatePosInPage: Int = 0
        private set

    /**
     * Used to decided whether the active candidate should be highlighted or
     * not. If user changes focus to composing view (The view to show Pinyin
     * string), the highlight in candidate view should be removed.
     */
    private var mEnableActiveHighlight = true

    /**
     * The page which is just calculated.
     */
    private var mPageNoCalculated = -1

    /**
     * The Drawable used to display as the background of the high-lighted item.
     */
    private val mActiveCellDrawable: Drawable

    /**
     * The Drawable used to display as separators between candidates.
     */
    private val mSeparatorDrawable: Drawable

    /**
     * Color to draw normal candidates generated by IME.
     */
    private val mImeCandidateColor: Int

    /**
     * Color to draw normal candidates Recommended by application.
     */
    private val mRecommendedCandidateColor: Int

    /**
     * Color to draw the normal(not highlighted) candidates, it can be one of
     * [.mImeCandidateColor] or [.mRecommendedCandidateColor].
     */
    private var mNormalCandidateColor: Int

    /**
     * Color to draw the active(highlighted) candidates, including candidates
     * from IME and candidates from application.
     */
    private val mActiveCandidateColor: Int

    /**
     * Text size to draw candidates generated by IME.
     */
    private var mImeCandidateTextSize = 0

    /**
     * Text size to draw candidates recommended by application.
     */
    private var mRecommendedCandidateTextSize = 0

    /**
     * The current text size to draw candidates. It can be one of
     * [.mImeCandidateTextSize] or [.mRecommendedCandidateTextSize].
     */
    private var mCandidateTextSize = 0

    /**
     * Paint used to draw candidates.
     */
    private val mCandidatesPaint: Paint

    /**
     * Used to draw footnote.
     */
    private val mFootnotePaint: Paint

    /**
     * The width to show suspension points.
     */
    private var mSuspensionPointsWidth = 0f

    /**
     * Rectangle used to draw the active candidate.
     */
    private val mActiveCellRect: RectF

    /**
     * Left and right margins for a candidate. It is specified in xml, and is
     * the minimum margin for a candidate. The actual gap between two candidates
     * is 2 * [.mCandidateMargin] + [.mSeparatorDrawable].
     * getIntrinsicWidth(). Because length of candidate is not fixed, there can
     * be some extra space after the last candidate in the current page. In
     * order to achieve best look-and-feel, this extra space will be divided and
     * allocated to each candidates.
     */
    private val mCandidateMargin: Float

    /**
     * Left and right extra margins for a candidate.
     */
    private var mCandidateMarginExtra = 0f

    /**
     * Rectangles for the candidates in this page.
     */
    private val mCandRects: Vector<RectF>

    /**
     * FontMetricsInt used to measure the size of candidates.
     */
    private var mFmiCandidates: FontMetricsInt? = null

    /**
     * FontMetricsInt used to measure the size of footnotes.
     */
    private var mFmiFootnote: FontMetricsInt? = null

    private val mTimer = PressTimer()

    private var mGestureDetector: GestureDetector? = null

    private val mLocationTmp = IntArray(2)

    init {
        val r = context.resources

        val conf = r.configuration
        if (conf.keyboard == Configuration.KEYBOARD_NOKEYS
            || conf.hardKeyboardHidden == Configuration.HARDKEYBOARDHIDDEN_YES
        ) {
            mShowFootnote = false
        }

        mActiveCellDrawable = r.getDrawable(R.drawable.candidate_hl_bg)
        mSeparatorDrawable = r.getDrawable(R.drawable.candidates_vertical_line)
        mCandidateMargin = r.getDimension(R.dimen.candidate_margin_left_right)

        mImeCandidateColor = r.getColor(R.color.candidate_color)
        mRecommendedCandidateColor = r.getColor(R.color.recommended_candidate_color)
        mNormalCandidateColor = mImeCandidateColor
        mActiveCandidateColor = r.getColor(R.color.active_candidate_color)

        mCandidatesPaint = Paint()
        mCandidatesPaint.isAntiAlias = true

        mFootnotePaint = Paint()
        mFootnotePaint.isAntiAlias = true
        mFootnotePaint.color = r.getColor(R.color.footnote_color)
        mActiveCellRect = RectF()

        mCandRects = Vector()
    }

    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
        val mOldWidth = measuredWidth
        val mOldHeight = measuredHeight

        setMeasuredDimension(
            getDefaultSize(
                suggestedMinimumWidth,
                widthMeasureSpec
            ), getDefaultSize(
                suggestedMinimumHeight,
                heightMeasureSpec
            )
        )

        if (mOldWidth != measuredWidth || mOldHeight != measuredHeight) {
            onSizeChanged()
        }
    }

    fun initialize(
        arrowUpdater: ArrowUpdater?, balloonHint: BalloonHint?,
        gestureDetector: GestureDetector?, cvListener: CandidateViewListener?
    ) {
        mArrowUpdater = arrowUpdater
        mBalloonHint = balloonHint
        mGestureDetector = gestureDetector
        mCvListener = cvListener
    }

    fun setDecodingInfo(decInfo: DecodingInfo?) {
        if (null == decInfo) return
        mDecInfo = decInfo
        mPageNoCalculated = -1

        if (mDecInfo!!.candidatesFromApp()) {
            mNormalCandidateColor = mRecommendedCandidateColor
            mCandidateTextSize = mRecommendedCandidateTextSize
        } else {
            mNormalCandidateColor = mImeCandidateColor
            mCandidateTextSize = mImeCandidateTextSize
        }
        if (mCandidatesPaint.textSize != mCandidateTextSize.toFloat()) {
            mCandidatesPaint.textSize = mCandidateTextSize.toFloat()
            mFmiCandidates = mCandidatesPaint.fontMetricsInt
            mSuspensionPointsWidth =
                mCandidatesPaint.measureText(SUSPENSION_POINTS)
        }

        // Remove any pending timer for the previous list.
        mTimer.removeTimer()
    }

    val activeCandiatePosGlobal: Int
        get() = mDecInfo!!.mPageStart[mPageNo] + activeCandiatePosInPage

    /**
     * Show a page in the decoding result set previously.
     *
     * @param pageNo Which page to show.
     * @param activeCandInPage Which candidate should be set as active item.
     * @param enableActiveHighlight When false, active item will not be
     * highlighted.
     */
    fun showPage(
        pageNo: Int, activeCandInPage: Int,
        enableActiveHighlight: Boolean
    ) {
        if (null == mDecInfo) return
        mPageNo = pageNo
        activeCandiatePosInPage = activeCandInPage
        if (mEnableActiveHighlight != enableActiveHighlight) {
            mEnableActiveHighlight = enableActiveHighlight
        }

        mUpdateArrowStatusWhenDraw = if (!calculatePage(mPageNo)) {
            true
        } else {
            false
        }

        invalidate()
    }

    fun enableActiveHighlight(enableActiveHighlight: Boolean) {
        if (enableActiveHighlight == mEnableActiveHighlight) return

        mEnableActiveHighlight = enableActiveHighlight
        invalidate()
    }

    fun activeCursorForward(): Boolean {
        if (!mDecInfo!!.pageReady(mPageNo)) return false
        val pageSize = (mDecInfo!!.mPageStart[mPageNo + 1]
                - mDecInfo!!.mPageStart[mPageNo])
        if (activeCandiatePosInPage + 1 < pageSize) {
            showPage(mPageNo, activeCandiatePosInPage + 1, true)
            return true
        }
        return false
    }

    fun activeCurseBackward(): Boolean {
        if (activeCandiatePosInPage > 0) {
            showPage(mPageNo, activeCandiatePosInPage - 1, true)
            return true
        }
        return false
    }

    private fun onSizeChanged() {
        mContentWidth = measuredWidth - paddingLeft - paddingRight
        mContentHeight = ((measuredHeight - paddingTop - paddingBottom) * 0.95f).toInt()
        /**
         * How to decide the font size if the height for display is given?
         * Now it is implemented in a stupid way.
         */
        var textSize = 1
        mCandidatesPaint.textSize = textSize.toFloat()
        mFmiCandidates = mCandidatesPaint.fontMetricsInt
        while (mFmiCandidates!!.bottom - mFmiCandidates!!.top < mContentHeight) {
            textSize++
            mCandidatesPaint.textSize = textSize.toFloat()
            mFmiCandidates = mCandidatesPaint.fontMetricsInt
        }

        mImeCandidateTextSize = textSize
        mRecommendedCandidateTextSize = textSize * 3 / 4
        if (null == mDecInfo) {
            mCandidateTextSize = mImeCandidateTextSize
            mCandidatesPaint.textSize = mCandidateTextSize.toFloat()
            mFmiCandidates = mCandidatesPaint.fontMetricsInt
            mSuspensionPointsWidth =
                mCandidatesPaint.measureText(SUSPENSION_POINTS)
        } else {
            // Reset the decoding information to update members for painting.
            setDecodingInfo(mDecInfo)
        }

        textSize = 1
        mFootnotePaint.textSize = textSize.toFloat()
        mFmiFootnote = mFootnotePaint.fontMetricsInt
        while (mFmiFootnote!!.bottom - mFmiFootnote!!.top < mContentHeight / 2) {
            textSize++
            mFootnotePaint.textSize = textSize.toFloat()
            mFmiFootnote = mFootnotePaint.fontMetricsInt
        }
        textSize--
        mFootnotePaint.textSize = textSize.toFloat()
        mFmiFootnote = mFootnotePaint.fontMetricsInt

        // When the size is changed, the first page will be displayed.
        mPageNo = 0
        activeCandiatePosInPage = 0
    }

    private fun calculatePage(pageNo: Int): Boolean {
        if (pageNo == mPageNoCalculated) return true

        mContentWidth = measuredWidth - paddingLeft - paddingRight
        mContentHeight = ((measuredHeight - paddingTop - paddingBottom) * 0.95f).toInt()

        if (mContentWidth <= 0 || mContentHeight <= 0) return false

        val candSize = mDecInfo!!.mCandidatesList.size

        // If the size of page exists, only calculate the extra margin.
        var onlyExtraMargin = false
        var fromPage = mDecInfo!!.mPageStart.size - 1
        if (mDecInfo!!.mPageStart.size > pageNo + 1) {
            onlyExtraMargin = true
            fromPage = pageNo
        }

        // If the previous pages have no information, calculate them first.
        for (p in fromPage..pageNo) {
            val pStart = mDecInfo!!.mPageStart[p]
            var pSize = 0
            var charNum = 0
            var lastItemWidth = 0f
            var xPos = 0f
            xPos += mSeparatorDrawable.intrinsicWidth.toFloat()
            while (xPos < mContentWidth && pStart + pSize < candSize) {
                val itemPos = pStart + pSize
                val itemStr = mDecInfo!!.mCandidatesList[itemPos]
                var itemWidth = mCandidatesPaint.measureText(itemStr)
                if (itemWidth < MIN_ITEM_WIDTH) itemWidth = MIN_ITEM_WIDTH

                itemWidth += mCandidateMargin * 2
                itemWidth += mSeparatorDrawable.intrinsicWidth.toFloat()
                if (xPos + itemWidth < mContentWidth || 0 == pSize) {
                    xPos += itemWidth
                    lastItemWidth = itemWidth
                    pSize++
                    charNum += itemStr.length
                } else {
                    break
                }
            }
            if (!onlyExtraMargin) {
                mDecInfo!!.mPageStart.add(pStart + pSize)
                mDecInfo!!.mCnToPage.add(mDecInfo!!.mCnToPage[p]!! + charNum)
            }

            var marginExtra = (mContentWidth - xPos) / pSize / 2

            if (mContentWidth - xPos > lastItemWidth) {
                // Must be the last page, because if there are more items,
                // the next item's width must be less than lastItemWidth.
                // In this case, if the last margin is less than the current
                // one, the last margin can be used, so that the
                // look-and-feeling will be the same as the previous page.
                if (mCandidateMarginExtra <= marginExtra) {
                    marginExtra = mCandidateMarginExtra
                }
            } else if (pSize == 1) {
                marginExtra = 0f
            }
            mCandidateMarginExtra = marginExtra
        }
        mPageNoCalculated = pageNo
        return true
    }

    override fun onDraw(canvas: Canvas) {
        super.onDraw(canvas)
        // The invisible candidate view(the one which is not in foreground) can
        // also be called to drawn, but its decoding result and candidate list
        // may be empty.
        if (null == mDecInfo || mDecInfo!!.isCandidatesListEmpty) return

        // Calculate page. If the paging information is ready, the function will
        // return at once.
        calculatePage(mPageNo)

        val pStart = mDecInfo!!.mPageStart[mPageNo]
        val pSize = mDecInfo!!.mPageStart[mPageNo + 1] - pStart
        val candMargin = mCandidateMargin + mCandidateMarginExtra
        if (activeCandiatePosInPage > pSize - 1) {
            activeCandiatePosInPage = pSize - 1
        }

        mCandRects.removeAllElements()

        var xPos = paddingLeft.toFloat()
        val yPos = ((measuredHeight -
                (mFmiCandidates!!.bottom - mFmiCandidates!!.top)) / 2
                - mFmiCandidates!!.top)
        xPos += drawVerticalSeparator(canvas, xPos)
        for (i in 0 until pSize) {
            var footnoteSize = 0f
            var footnote: String? = null
            if (mShowFootnote) {
                footnote = (i + 1).toString()
                footnoteSize = mFootnotePaint.measureText(footnote)
                assert(footnoteSize < candMargin)
            }
            var cand = mDecInfo!!.mCandidatesList[pStart + i]
            var candidateWidth = mCandidatesPaint.measureText(cand)
            var centerOffset = 0f
            if (candidateWidth < MIN_ITEM_WIDTH) {
                centerOffset = (MIN_ITEM_WIDTH - candidateWidth) / 2
                candidateWidth = MIN_ITEM_WIDTH
            }

            val itemTotalWidth = candidateWidth + 2 * candMargin

            if (activeCandiatePosInPage == i && mEnableActiveHighlight) {
                mActiveCellRect[xPos, (paddingTop + 1).toFloat(), xPos
                        + itemTotalWidth] = (height - paddingBottom - 1).toFloat()
                mActiveCellDrawable.setBounds(
                    mActiveCellRect.left.toInt(),
                    mActiveCellRect.top.toInt(), mActiveCellRect.right.toInt(),
                    mActiveCellRect.bottom.toInt()
                )
                mActiveCellDrawable.draw(canvas)
            }

            if (mCandRects.size < pSize) mCandRects.add(RectF())
            mCandRects.elementAt(i)[xPos - 1, (yPos + mFmiCandidates!!.top).toFloat(), xPos + itemTotalWidth + 1] =
                (yPos + mFmiCandidates!!.bottom).toFloat()

            // Draw footnote
            if (mShowFootnote) {
                canvas.drawText(
                    footnote!!, xPos + (candMargin - footnoteSize)
                            / 2, yPos.toFloat(), mFootnotePaint
                )
            }

            // Left margin
            xPos += candMargin
            if (candidateWidth > mContentWidth - xPos - centerOffset) {
                cand = getLimitedCandidateForDrawing(
                    cand,
                    mContentWidth - xPos - centerOffset
                )
            }
            if (activeCandiatePosInPage == i && mEnableActiveHighlight) {
                mCandidatesPaint.color = mActiveCandidateColor
            } else {
                mCandidatesPaint.color = mNormalCandidateColor
            }
            canvas.drawText(
                cand, xPos + centerOffset, yPos.toFloat(),
                mCandidatesPaint
            )

            // Candidate and right margin
            xPos += candidateWidth + candMargin

            // Draw the separator between candidates.
            xPos += drawVerticalSeparator(canvas, xPos)
        }

        // Update the arrow status of the container.
        if (null != mArrowUpdater && mUpdateArrowStatusWhenDraw) {
            mArrowUpdater!!.updateArrowStatus()
            mUpdateArrowStatusWhenDraw = false
        }
    }

    private fun getLimitedCandidateForDrawing(
        rawCandidate: String,
        widthToDraw: Float
    ): String {
        var subLen = rawCandidate.length
        if (subLen <= 1) return rawCandidate
        do {
            subLen--
            val width = mCandidatesPaint.measureText(rawCandidate, 0, subLen)
            if (width + mSuspensionPointsWidth <= widthToDraw || 1 >= subLen) {
                return rawCandidate.substring(0, subLen) +
                        SUSPENSION_POINTS
            }
        } while (true)
    }

    private fun drawVerticalSeparator(canvas: Canvas, xPos: Float): Float {
        mSeparatorDrawable.setBounds(
            xPos.toInt(),
            paddingTop, xPos.toInt() + mSeparatorDrawable.intrinsicWidth, measuredHeight
                    - paddingBottom
        )
        mSeparatorDrawable.draw(canvas)
        return mSeparatorDrawable.intrinsicWidth.toFloat()
    }

    private fun mapToItemInPage(x: Int, y: Int): Int {
        // mCandRects.size() == 0 happens when the page is set, but
        // touch events occur before onDraw(). It usually happens with
        // monkey test.
        if (!mDecInfo!!.pageReady(mPageNo) || mPageNoCalculated != mPageNo || mCandRects.size == 0) {
            return -1
        }

        val pageStart = mDecInfo!!.mPageStart[mPageNo]
        val pageSize = mDecInfo!!.mPageStart[mPageNo + 1] - pageStart
        if (mCandRects.size < pageSize) {
            return -1
        }

        // If not found, try to find the nearest one.
        var nearestDis = Float.MAX_VALUE
        var nearest = -1
        for (i in 0 until pageSize) {
            val r = mCandRects.elementAt(i)
            if (r.left < x && r.right > x && r.top < y && r.bottom > y) {
                return i
            }
            val disx = (r.left + r.right) / 2 - x
            val disy = (r.top + r.bottom) / 2 - y
            val dis = disx * disx + disy * disy
            if (dis < nearestDis) {
                nearestDis = dis
                nearest = i
            }
        }

        return nearest
    }

    // Because the candidate view under the current focused one may also get
    // touching events. Here we just bypass the event to the container and let
    // it decide which view should handle the event.
    override fun onTouchEvent(event: MotionEvent): Boolean {
        return super.onTouchEvent(event)
    }

    fun onTouchEventReal(event: MotionEvent): Boolean {
        // The page in the background can also be touched.
        if (null == mDecInfo || !mDecInfo!!.pageReady(mPageNo)
            || mPageNoCalculated != mPageNo
        ) return true
        val x = event.x.toInt()
        val y = event.y.toInt()

        if (mGestureDetector!!.onTouchEvent(event)) {
            mTimer.removeTimer()
            mBalloonHint!!.delayedDismiss(0)
            return true
        }

        var clickedItemInPage = -1

        when (event.action) {
            MotionEvent.ACTION_UP -> {
                clickedItemInPage = mapToItemInPage(x, y)
                if (clickedItemInPage >= 0) {
                    invalidate()
                    mCvListener!!.onClickChoice(
                        clickedItemInPage
                                + mDecInfo!!.mPageStart[mPageNo]
                    )
                }
                mBalloonHint!!.delayedDismiss(BalloonHint.TIME_DELAY_DISMISS.toLong())
            }

            MotionEvent.ACTION_DOWN -> {
                clickedItemInPage = mapToItemInPage(x, y)
                if (clickedItemInPage >= 0) {
                    showBalloon(clickedItemInPage, true)
                    mTimer.startTimer(
                        BalloonHint.TIME_DELAY_SHOW.toLong(), mPageNo,
                        clickedItemInPage
                    )
                }
            }

            MotionEvent.ACTION_CANCEL -> {}
            MotionEvent.ACTION_MOVE -> {
                clickedItemInPage = mapToItemInPage(x, y)
                if (clickedItemInPage >= 0
                    && (clickedItemInPage != mTimer.activeCandOfPageToShow || mPageNo != mTimer
                        .pageToShow)
                ) {
                    showBalloon(clickedItemInPage, true)
                    mTimer.startTimer(
                        BalloonHint.TIME_DELAY_SHOW.toLong(), mPageNo,
                        clickedItemInPage
                    )
                }
            }
        }
        return true
    }

    private fun showBalloon(candPos: Int, delayedShow: Boolean) {
        mBalloonHint!!.removeTimer()

        val r = mCandRects.elementAt(candPos)
        val desired_width = (r.right - r.left).toInt()
        val desired_height = (r.bottom - r.top).toInt()
        mBalloonHint!!.setBalloonConfig(
            mDecInfo!!.mCandidatesList[mDecInfo!!.mPageStart[mPageNo] + candPos], 44f, true,
            mImeCandidateColor, desired_width, desired_height
        )

        getLocationOnScreen(mLocationTmp)
        mHintPositionToInputView[0] = (mLocationTmp[0]
                + (r.left - (mBalloonHint!!.width - desired_width) / 2).toInt())
        mHintPositionToInputView[1] = -mBalloonHint!!.height

        var delay: Long = BalloonHint.TIME_DELAY_SHOW.toLong()
        if (!delayedShow) delay = 0
        mBalloonHint!!.dismiss()
        if (!mBalloonHint!!.isShowing) {
            mBalloonHint!!.delayedShow(delay, mHintPositionToInputView)
        } else {
            mBalloonHint!!.delayedUpdate(0, mHintPositionToInputView, -1, -1)
        }
    }

    private inner class PressTimer : Handler(), Runnable {
        var isPending: Boolean = false
            private set
        var pageToShow: Int = 0
            private set
        var activeCandOfPageToShow: Int = 0
            private set

        fun startTimer(afterMillis: Long, pageNo: Int, activeInPage: Int) {
            mTimer.removeTimer()
            postDelayed(this, afterMillis)
            isPending = true
            pageToShow = pageNo
            activeCandOfPageToShow = activeInPage
        }

        fun removeTimer(): Boolean {
            if (isPending) {
                isPending = false
                removeCallbacks(this)
                return true
            }
            return false
        }

        override fun run() {
            if (pageToShow >= 0 && activeCandOfPageToShow >= 0) {
                // Always enable to highlight the clicked one.
                showPage(pageToShow, activeCandOfPageToShow, true)
                invalidate()
            }
            isPending = false
        }
    }

    companion object {
        /**
         * The minimum width to show a item.
         */
        private const val MIN_ITEM_WIDTH = 22f

        /**
         * Suspension points used to display long items.
         */
        private const val SUSPENSION_POINTS = "..."
    }
}
